version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - public/*
            - node_modules/*

  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: public
          to: 's3://journey.staging.prog-8.com'
          overwrite: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: fix-deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dummy
