version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0

jobs:
  build_staging:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - public/*
            - node_modules/*

  deploy_staging:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: public
          to: $S3_BUCKET
          overwrite: true

workflows:
  version: 2
  build-and-deploy-staging:
    jobs:
      - build_staging:
          filters:
            branches:
              only: fix-deploy
      - deploy_staging:
          context: journey-staging
          requires:
            - build_staging
          filters:
            branches:
              only: fix-deploy
